### ISSUE TITLE
Não está incluindo os compromissos na agenda.

### ISSUE THREAD

**Issue by flaviojoaofelix** [michaelcaxias/trybe-scheduler#73]
Olá!
Fazem mais ou menos 3 dias que não consigo utilizar a ferramenta.

No primeiro dia, não estava conseguindo colar os agendamentos no campo para inclusão e consequentemente, não consegui adicionar os compromissos na agenda.

Nos últimos dois dias, estou conseguindo colar os agendamentos no campo, mas ao clicar em adicionar, nada acontece.

No console posso perceber uma mensagem de ERRO 401 (Bad Request) relacionado a promise.

**Comment by cauemustafa** [comment]
Estou com o mesmo problema. Essa semana não consegui adicionar nada na agenda.

Uncaught (in promise) _l {
message: 'Request failed with status code 401',
name: 'AxiosError', code: 'ERR_BAD_REQUEST',
config: {…},
request: XMLHttpRequest,
 …}

**Comment by cauemustafa** [comment]
@flaviojoaofelix tenta deslogar e logar novamente, aqui o problema foi resolvido simples assim!

**Comment by cauemustafa** [comment]
@michaelcaxias hoje eu tive que deslogar e logar novamente para adicionar os compromissos da agenda, estava dando o mesmo erro. O status 401 é sobre permissões, talvez não seja válido adicionar um token com limite de tempo pra deslogar, antes do token do google vencer.

> ```
> Uncaught (in promise) _l {
> message: 'Request failed with status code 401',
> name: 'AxiosError', code: 'ERR_BAD_REQUEST',
> config: {…},
> request: XMLHttpRequest,
>  …}
> ```

**Comment by flaviojoaofelix** [comment]
> @flaviojoaofelix tenta deslogar e logar novamente, aqui o problema foi resolvido simples assim!

Fiz isso e acabou voltando a funcionar na semana passada. Já havia feito esse passo antes por indicação do João, mas não havia funcionado. Acabei voltando a faze-lo após você comentar e realmente funcionou.

Porém hoje, novamente estou tendo problemas.
Dessa vez, como na primeira, não consigo colar os compromissos no campo para o agendamento.

Isso está acontecendo tanto no Firefox quanto no Chrome.

**Comment by michaelcaxias** [comment]
Vou dar uma analisada hoje no comportamento pra entender o que tá acontecendo.

**Comment by michaelcaxias** [comment]
Subi uma correção validando e deslogando caso haja uma resposta com o status 401.

commit: https://github.com/michaelcaxias/trybe-scheduler/commit/f521d065a4f619753a1d2f621dadcbe3716e1bda

@flaviojoaofelix depois tenta novamente? obrigado

**Comment by flaviojoaofelix** [comment]
acabei de testar e está funcionando!
qualquer mudança te informo por aqui novamente.

obrigado @michaelcaxias

**Comment by cauemustafa** [comment]
> Subi uma correção validando e deslogando caso haja uma resposta com o status 401.
> 
> commit: [f521d06](https://github.com/michaelcaxias/trybe-scheduler/commit/f521d065a4f619753a1d2f621dadcbe3716e1bda)
> 
> @flaviojoaofelix depois tenta novamente? obrigado

Ficou muito bom, @michaelcaxias! Parabéns pela rapidez na resolução do problema! #VQV
